const ADD_CHILD = 'ADD_NAME';
const TOGGLE_COMPLETE = 'TOGGLE_COMPLETE';
const UPDATE_CHILDS = 'UPDATE_CHILDS';
const SHORT_CHILDS_NAME = 'SHORT_CHILDS_NAME';

const types = {
  ADD_CHILD,
  TOGGLE_COMPLETE,
  UPDATE_CHILDS,
  SHORT_CHILDS_NAME,
};

export default types;
